---
- name: yoloify setup
  hosts: "tag_{{ server }}"
  user: "{{ env_user }}"
  sudo: True

  vars:
    git_branch: "{{ branch }}"

  pre_tasks:
    - include: tasks/pre-installation.yml

  roles:
    - pip
    - supervisor

  post_tasks:
    - include: tasks/build.yml
    - include: tasks/celery.yml
    - include: tasks/post-installation.yml